name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu_latest
    steps: 
      - name: Print Greeting
        run: echo 'Hello world'
      - name: Print Goodbye
        run: echo 'Goodbye'
